#!/usr/bin/perl -w
######################################################################
#
# Edwin Huffstutler, <edwinh@computer.org>
# $Id$
# $Name$
#
#         >>>> See the README file <<<<
#
# USAGE:
#
#  flexbackup -help                : this message
#
#  flexbackup -fs all              : backup all filesystems, level 0
#  flexbackup -fs <x>              : backup filesystem <x>, level 0
#  flexbackup -fs all -level <n>   : backup all filesystems, level n
#  flexbackup -fs <x> -level <n>   : backup filesystem <x>, level n
#
#  flexbackup -list                : list files in archive at current
#                                    tape position
#
#  flexbackup -extract             : restore from current tape position
#                                    into your current working directory
#
#  flexbackup -restore             : as above, but interactive restore
#                                    (dump type only for now)
#
#  flexbackup -compare             : compare archive at current tape position
#                                    with the files in your current directory
#
#  flexbackup -toc                 : list tape table of contents
#                                    with Linux ftape only
#
#  flexbackup [opt] -c <file>      : use <file> instead of /etc/flexbackup.conf
#                                    for configuration
#
#  flexbackup [opt] -type <x>      : override $backuptype from config file
#
#  flexbackup -fs <x> -erase       : force a rewind/erase before backup
#  flexbackup -fs <x> -noreten     : don't retension for level 0 "all" backups
#
######################################################################

use Getopt::Long;
use English;

# To make -w shuttup for variables I only reference once
use vars qw($filesystems);

# No output buffering
$OUTPUT_AUTOFLUSH = 1;

%opt = ();
if (! &GetOptions(\%opt,
		  "help",
		  "c=s",
		  "level=i",
		  "fs=s",
                  "extract",
                  "restore",
                  "list",
                  "compare",
                  "toc",
                  "type=s",
                  "noreten",
                  "erase"
		  )) {
    &usage();
    exit(0);
}

# Give usage message
if (defined($opt{'help'})) {
    &usage();
    exit(0);
}

# Get/read config file
&readconfigfile();

# Sanity check things
&optioncheck();

# Get date string
chomp($date=`date +%Y%m%d`);

# Set blocksize
$_ = $blksize * 1024;
system("$mt -f $device setblk $_");
if ($?) {
    die("Error from $mt setblk $_, exiting...\n");
}


if (defined($opt{'restore'})) {
    &restore_routine();

} elsif (defined($opt{'extract'})) {
    &extract_routine();

} elsif (defined($opt{'compare'})) {
    &compare_routine();

} elsif (defined($opt{'list'})) {
    &list_routine();

} elsif (defined($opt{'fs'})) {
    &backup_routine();

} elsif (defined($opt{'toc'})) {

    if ($ftape eq 'true') {
	system("$mt -f $device rewind");
	exec("vtblc -p -f $rawdevice");
	die("Failed exec of vtblc\n");
    } else {
	die("-toc only implemented for ftape under Linux\n");
    }

} else {
    print "Nothing to do!\n";

}

exit(0);

######################################################################
# Backup
######################################################################
sub backup_routine {

    # Get backup level...
    if (defined($opt{'level'})) {
        $level = $opt{'level'};
    } else {
        $level = 0;
    }

    # Die if no fs specified
    if (!defined($opt{'fs'})) {
        &usage();
        exit(0);
    }

    &log('$Name$ $Id$ ');
    &log("Doing level $level backup of $opt{fs} using $backuptype");

    # Figure out log file name & empty log file
    $label = &get_label($opt{'fs'});
    $log = "$logdir/$prefix$label.$level.$date";
    if (! open(LOG,">$log")) {
        die "Can't write to $log: $!\n";
    }
    close(LOG);

    # Remove old incremental log files
    # ("old" = any higher-numbered logs for this label)
    opendir(DIR,"$logdir") or die("Can't open logdir: $!\n");
    @files = readdir(DIR);
    foreach (@files) {
        next if (! m/^$prefix$label\.([0-9])\.([0-9]+)$/);
        my $olddate = $2;
        if ($1 > $level) {
            print "Removing old level $1 log of $opt{fs} ($olddate)\n";
            unlink("$logdir/$_") or warn("Can't remove $_: $!\n");
        }
    }
    close(DIR);

    # Remove old incremental stamp files
    # ("old" = any higher-numbered logs for this label)
    opendir(DIR,"$stampdir") or die("Can't open stampdir: $!\n");
    @files = readdir(DIR);
    foreach (@files) {
        next if (! m/^$sprefix\.$label\.([0-9])$/);
        if ($1 > $level) {
            print "Removing old level $1 timestamp of $opt{fs}\n";
            unlink("$stampdir/$_") or warn("Can't remove $_: $!\n");
        }
    }
    close(DIR);


    ##########################
    #
    # Main backup routine
    #
    ##########################
    &line();

    if ($opt{'fs'} eq 'all') {

        &log("(all = $filesystems)");

        # All filesystems
        if ($level eq "0") {

            # All
            # Level zero - rewind and erase a new tape
            if (!defined($opt{'noreten'})) {
                &log('Retensioning tape...');
                &mt('retension');
            }
            &log('Erasing tape...');
            &mt('erase');
            $nextfile = 0;

        } else {

            # All
            # Incremental backup - list what's on it, then go to end of tape
            if (!defined($opt{'erase'})) {
                $nextfile = &contents();
                &log('Making sure tape is at end of data...');
                &mt('endofdata');
            } else {
                $nextfile = 0;
                &log('Rewinding & erasing tape...');
                &mt('rewind');
                &mt('erase');
            }
        }

        # Show tape position
        &line();
        &mt('query');

        # Iterate over the filesystems and back 'em up
        foreach (split(/\s+/,$filesystems)) {
            &backup($backuptype,$_,$nextfile);
            $tag{$nextfile} = "$backuptype $_ ($level)";
            $nextfile++;
        }

        # Rewind
        &line();
        &log("Rewinding...\n");
        &mt('rewind');

        # Only ftape has the toc capability
        if ($ftape eq 'true') {
            &log('Updating table of contents...');
            foreach (keys %tag) {
                &tag($_,$tag{$_});
            }
        }

    } else {

        # Just one filesystem
        if (!defined($opt{'erase'})) {
            $nextfile = &contents();
            &log('Making sure tape is at end of data...');
            &mt('endofdata');
        } else {
            $nextfile = 0;
            &log('Rewinding & erasing tape...');
            &mt('rewind');
            &mt('erase');
        }
        &line();
        &mt('query');
        &backup($backuptype,$opt{'fs'},$nextfile);
        &line();
        &log("Rewinding...");
        &mt('rewind');
        if ($ftape eq 'true') {
            &log('Updating table of contents...');
            &tag($nextfile,"$backuptype $opt{'fs'} ($level)");
        }
    }

    # Print out new contents
    &contents();

    exit(0);
}

######################################################################
# Rewind & print TOC using vtblc
# returns an integer that is the next file number
######################################################################
sub contents {
    my($output,$filenumber);

    if ($ftape eq "true") {
        &mt('rewind');
        &log('');
        $output=`vtblc -p -f $rawdevice 2>&1`;
        &log($output);
        &log('');
        $filenumber = -1;
        foreach (split("\n",$output)) {
            # Nr  Id          Label
            #-------------------------------
            #  0 VTBL "/var (level 9)
            next if m/^\s+Nr\s+/;
            next if m/^----------/;
            if (m/^\s+(\d+)\s+\S+\s+\"/) {
                $filenumber = $1;
            }
        }

    } else {

        $filenumber = 0;
    }

    $filenumber++;
    return($filenumber);
}

######################################################################
# Modify a table of contents entry
######################################################################
sub tag {
    my($filenum,$title) = @_;
    system("vtblc -f $rawdevice -# $filenum -m date -m label=\'$title\'");
}

######################################################################
# Backup a filesystem
######################################################################
sub backup {

    my($type,$dir,$filenum) = @_;
    my($localdir,$string,$tapehost,$remote);

    $localdir = $dir;
    if ($localdir =~ s/^(.+):(.+)$/$2/) {
	$remote = $1;
	chomp($tapehost = `hostname`);
    } else {
        $remote = '';
    }

    if ($type eq 'dump') {
	$string = &backup_dump($localdir,$remote,$tapehost);
    } elsif ($type eq 'afio') {
	$string = &backup_afio($localdir,$remote,$tapehost);
    } elsif ($type eq 'tar') {
	$string = &backup_tar($localdir,$remote,$tapehost);
    } elsif ($type eq 'cpio') {
	$string = &backup_cpio($localdir,$remote,$tapehost);
    }

    &line();
    my $stamp = &get_label($dir);
    &log("Timestamp $stampdir/$sprefix.$stamp.$level");
    system("touch $stampdir/$sprefix.$stamp.$level");

    &line();
    &log("Running \"$string\"");

    # If we started with level 0 and all, we know the file number,
    # since we erased the tape
    # (or if using ftape/vtblc, since we can find the file number)
    # (or if we had -erase on the commandline)
    if ((($opt{'fs'} eq "all") and ($level eq "0"))
        or
        ($ftape eq "true")
        or
        ($opt{'erase'})) {
        &log("Backup will be file number $filenum");
    }

    # Enough fooling around... run it
    &line();
    system("$string 2>&1 | tee -a $log");
    if ($?) {
	&log("Error from $type backup, exiting....\n");
	exit(1);
    }

    # tar is causing me fits...  mt right after archive operations is giving i/o errors
    if ($type eq 'tar') {
        sleep 5;
    }

    # Show where we are on the tape
    &line();
    &mt('query');
}


######################################################################
# Return command to backup a filesystem using dump
######################################################################
sub backup_dump {
    my($label,$dir,$remote,$tapehost) = @_;
    my $string = '';

    if ($remote) {
        $string .= "$remoteshell $remote \"r";
    }

    $string .= "dump $level" . "uBbf $dump_length $blksize";

    if ($remote) {
        $string .= " $tapehost:$device $dir\"";
    } else {
        $string .= " $device $dir";
    }

    return($string);
}


######################################################################
# Return command to backup a filesystem using afio
######################################################################
sub backup_afio {
    my($label,$dir,$remote,$tapehost) = @_;
    my $string  = '';

    if ($remote) {
	$string  .= "$remoteshell $remote -n \"";
    }

    $string .= "cd $dir; find . -xdev";

    if ($level ne "0") {
        my $last_stamp = &get_latest_stamp($label,$level,$remote);
        $string .= " -newer $last_stamp";
    }

    $string .= " -print | afio -o $afio_compress $afio_verbose -b $afio_blksize -c $afio_buffer";

    if ($remote) {
        $string .= " -B $tapehost%$remoteshell:$device\"";
    } else {
        $string .= " -B $device";
    }

    return($string);
}

######################################################################
# Return command to backup a filesystem using cpio
######################################################################
sub backup_cpio {
    my($label,$dir,$remote,$tapehost) = @_;
    my $string = '';

    if ($remote) {
        $string .= "$remoteshell $host -n \"";
    }

    $string .= "cd $dir; find . -xdev";

    if ($level ne "0") {
        my $last_stamp = &get_latest_stamp($label,$level,$remote);
        $string .= " -newer $last_stamp";
    }

    $string .= " -print | cpio -o $cpio_verbose -H $cpio_format -C $cpio_blksize";

    if ($remote) {
        $string .= " -F $tapehost:$device\"";
    } else {
        $string .= " -F $device";
    }

    return($string);
}

######################################################################
# Return command to backup a filesystem using tar
######################################################################
sub backup_tar {
    my($fs,$dir,$remote,$tapehost) = @_;
    my $string = '';

    if ($remote) {
        $string  .= "$remoteshell $remote \"";
    }


    $string .= "tar -C $dir -c $tar_compress $tar_verbose -b $tar_blksize -l";

    if ($level ne "0") {
        # With this one we dont have to copy the stampfile to the remote system
        # since we only need the string from date -r on the stamp file
        my $last_stamp = &get_latest_stamp($label,$level,'');
        mt $tardate;
        chomp($tardate = `date -r $last_stamp`)
        $string .= " -N \'$tardate\'";
    }

    if ($remote) {
        $string .= " --rsh-command $remoteshell -f $tapehost:$device .\"";
    } else {
        $string .= " -f $device .";
    }

    return($string);
}

######################################################################
# List the files in an archive
######################################################################
sub list_routine {

    if ($backuptype eq 'dump') {
        &mt('query');
        &line();
	system("restore -t -b $blksize -f $device");
        &line();
        &mt('query');
        exit;

    } elsif ($backuptype eq 'afio') {
        &mt('query');
        &line();
        system("afio -t $afio_verbose -b $afio_blksize -B $device");
        &line();
        &mt('query');
        exit;

    } elsif ($backuptype eq 'tar') {
        &mt('query');
        &line();
        system("tar -t $tar_verbose $tar_compress -b $tar_blksize -f $device");
        &line();
        &mt('query');
        exit;

    } elsif ($backuptype eq 'cpio') {
        &mt('query');
        &line();
        system("cpio -t $cpio_verbose -H $cpio_format -C $cpio_blksize -F $device");
        &line();
        &mt('query');
        exit;

    }
}

######################################################################
# Extract an archive to current directory
######################################################################
sub extract_routine {

    if ($backuptype eq 'dump') {
        &mt('query');
        &line();
	system("restore -r -v -b $blksize -f $device");
        &line();
        &mt('query');
	exit;

    } elsif ($backuptype eq 'afio') {
        &mt('query');
        &line();
        system("afio -i -x $afio_compress $afio_verbose -b $afio_blksize -B $device");
        &line();
        &mt('query');
        exit;

    } elsif ($backuptype eq 'tar') {
        &mt('query');
        &line();
        system("tar -x -p $tar_compress $tar_verbose -b $tar_blksize -f $device");
        &line();
        &mt('query');
        exit;

    } elsif ($backuptype eq 'cpio') {
        &mt('query');
        &line();
        system("cpio -i -m -d $cpio_verbose -H $cpio_format -C $cpio_blksize -F $device");
        &line();
        &mt('query');
        exit;

    }
}

######################################################################
# Compare an archive to current directory
######################################################################
sub compare_routine {

    if ($backuptype eq 'dump') {
        &mt('query');
        &line();
	system("restore -C -b $blksize -f $device");
        &line();
        &mt('query');
	exit;

    } elsif ($backuptype eq 'afio') {
        &mt('query');
        &line();
        system("afio -r $afio_compress -b $afio_blksize -B $device");
        &line();
        &mt('query');
	exit;

    } elsif ($backuptype eq 'tar') {
        &mt('query');
        &line();
        system("tar -d $tar_compress -b $tar_blksize -f $device");
        &line();
        &mt('query');
	exit;

    } elsif ($backuptype eq 'cpio') {
        die("cpio not capable of comparing files\n");

    }
}

######################################################################
# Interactive restore
######################################################################
sub restore_routine {

    if ($backuptype eq 'dump') {
        &mt('query');
        &line();
	system("restore -i -v -b $blksize -f $device");
        &line();
        &mt('query');
	exit;

    } else {
        die("Interactive restore for $backuptype not done yet\n");
    }
}

######################################################################
# Return the "label" name of the filesystem/dir
######################################################################
sub get_label {

    my($label) = shift(@_);

    $label =~ s:^/::;
    $label =~ s:/:-:g;
    if ($label eq '') {
        $label = 'root';
    } elsif ($label =~ m/^(.+):-$/) {
        $label = "$1:root";
    }

    return($label);

}

######################################################################
# Echo message to screen and log
######################################################################
sub log {
    my($msg) = @_;
    print "$msg\n";
    if (defined($log)) {
        open(LOG,">>$log");
        print LOG "$msg\n";
        close(LOG);
    }
}

######################################################################
# Echo a line to both screen and log
######################################################################
sub line {
    print "----------------------------------------\n";
    if (defined($log)) {
        open(LOG,">>$log");
        print LOG "----------------------------------------\n";
        close(LOG);
    }
}

######################################################################
# Read configuration file
######################################################################
sub readconfigfile {
    if (defined($opt{'c'})) {
        $configfile = $opt{'c'};
    } else {
        $configfile = "/etc/flexbackup.conf";
    }
    if (! -r $configfile) {
        die("config file $configfile: $!");
    }
    system("perl -c $configfile 2>&1");
    if ($?) {
        die("syntax error in config file $configfile");
    }
    require "$configfile";

}

######################################################################
# Do a tape operation
######################################################################
sub mt {
    my($operation) = @_;

    if ($operation eq 'query') {
        if ($ftape eq 'true') {
            $operation = 'getsize';
        } else {
            $operation = 'status';
        }
    }

    if ($operation eq 'endofdata') {
        if ($ftape eq 'true') {
            $operation = 'eom';
        } else {
            $operation = 'eod';
        }
    }

    if (defined($log)) {
        system("$mt -f $device $operation 2>&1 | tee -a $log");
    } else {
        system("$mt -f $device $operation 2>&1");
    }
    if ($?) {
	&log("Error from $mt $operation, exiting....\n");
        exit(1);
    }
}

######################################################################
# Option error checking
######################################################################
sub optioncheck {

    # ftape support
    if (defined($ftape)) {
	if ($ftape eq 'true') {
	    $mt = 'ftmt';
	} elsif ($ftape eq 'false') {
	    $mt = 'mt';
	} else {
	    die("\$ftape must be defined as true or false\n");
	}
    } else {
	die("\$ftape must be defined as true or false\n");
    }

    # log/stamp files
    if (defined($logdir)) {
	if (! -d $logdir) {
            mkdir("$logdir",0755) or die("Can't mkdir $logdir: $!");
	}
    } else {
	die("$logdir must be defined\n");
    }
    if (defined($stampdir)) {
        if (! -d $stampdir) {
            mkdir("$stampdir",0755) or die("Can't mkdir $stampdir: $!");
        }
    } else {
        die("$stampdir must be defined\n");
    }

    # archive type
    if (defined($opt{'type'})) {
        $backuptype = $opt{'type'};
    }

    # Type-specific setup
    if (defined($backuptype)) {

	if ($backuptype eq 'afio') {

            # Compress flag
            if ($afio_compress eq "true") {
                $afio_compress = "-Z";
            } else {
                $afio_compress = "";
            }

            # Verbose flag
            if ($afio_verbose eq "true") {
                $afio_verbose = "-v -z";
            } else {
                $afio_verbose = "";
            }

            # For afio, blocksize needs k appended
            $afio_blksize = $blksize . "k";

	} elsif ($backuptype eq 'dump') {

	} elsif ($backuptype eq 'tar') {

            # Compress flag
            if ($tar_compress eq "true") {
                $tar_compress = "-z";
            } else {
                $tar_compress = "";
            }

            # Verbose flag
            if ($tar_verbose eq "true") {
                $tar_verbose = "-v --totals";
            } else {
                $tar_verbose = "";
            }

            # For tar, blocks are in 512-byte units
            # not 1024 (1k) like dump, afio
            $tar_blksize = $blksize * 2;

	} elsif ($backuptype eq 'cpio') {

            # Verbose flag
            if ($cpio_verbose eq "true") {
                $cpio_verbose = "-v";
            } else {
                $cpio_verbose = "";
            }

            # For cpio, blocks are in bytes
            # not 1024 (1k) like dump, afio
            $cpio_blksize = $blksize * 1024;

	} else {
	    die("\$backuptype must be defined as afio, dump, tar, or cpio\n");
	}
    } else {
	die("\$backuptype must be defined as afio, dump, tar, or cpio\n");
    }


}

######################################################################
# Print usage summary from the header
######################################################################
sub usage {
    open(FILE,"$0") or die "Can't open $0: $!\n";
    while(<FILE>) {
	last if (m/^\#\s+USAGE:/);
    }
    while(<FILE>) {
	last if (m/^\#\#\#\#\#\#\#/);
	s/^\#//;
	print;
    }
    close(FILE);
}
