.TH MULTIBUF 1 "Multi-Volume Archive Management Utility" 
.SH NAME
multibuf \- manage multiple volume archives
.SH SYNOPSIS
\fBmultibuf\fR [options] filename
.SH DESCRIPTION
\fBmultibuf\fR  is a tape archive manager which provides the
capability of extending a single logical archive over multiple
physical media volumes.
.br
\fBmultibuf\fR is part of the \fBKBackup\fR package. See the
documentation of \fBKBackup\fR for more information and the
conditions of use.
.SH OPTIONS
.I "\-r, "\--read
.RS
Set read mode.
The archive is read from the device named in filename
and written to stdout.
.RE
.TP
.I "\-w, \--write (default)
.RS
Set write mode.
The archive is read from stdin
and written to the device named in filename.
.RE
.TP
.I "\-v, "\--verbose
.RS
Enable verbose progress reporting.
.RE
.TP
.I "\-m, "\--multibuf buffers
.RS
This enables real double-buffering using shared memory (Linux only)
which can be used to keep a tape drive streaming continuously. The parameter
is the number of shared buffers to use (at least 2).
.RE
.TP
.I "\-b, "\--blocksize byte_count (default = 1024)
.RS
This sets the minimal size of the data blocks used for 
the single write/read calls.
Normally you should not change this.
.RE
.TP
.I "\-n, "\--nblocks block_count (default = 100, minimum = 5)
.RS
Use this option to change the size of the buffers used by multibuf.
.RE
.TP
.I "\-c, "\--command "shell-command"
.RS
Set command1, which is executed at end of medium.
The default is
"dialog --title \"KBackup's MultiBuf\" --yesno \"Continue
with next volume?\" 5 40 </dev/tty >/dev/tty".
This command is expected to exit with a status of 0 to indicate that a
retry should be performed.
.RE
.TP
.I "\-C, "\--command2 "shell-command"
.RS
Set command2, which is executed at beginning of medium.
The default is "mt rewind </dev/tty >/dev/tty".
The exit status of this command is not checked.
.RE
.TP
.I "\-R, "\--retry-command "shell-command"
.RS
Set command to execute when finding  wrong sequence number.
The default is "dialog --title "KBackup's MultiBuf" --yesno "Detected
wrong sequence number.  Retry?" 6 50 </dev/tty >/dev/tty".
This command is expected to exit with a status of 0 to indicate that a
retry should be performed.
.RE
.TP
.I "\-1, "\--end-only
.RS
Only execute command at end of media.
This option disables command2 processing.
.RE
.TP
.I "\-2, "\--begin-and-end (default)
.RS
Exeute commands at end and begin of media.
This option enables command2 processing.
.RE
.TP
.I "\-s, "\--settings
.RS
Display settings.
.RE
.TP
.I "\-x, "\--exit
.RS
Exit after processing options (for testing).
.RE
.TP
.I "\-h, "\--header
.RS
Add header/sequence information to data.
This writes media headers with volume sequencing and block
sizing information when writing an archive, or utilizes these
headers when reading an archive.
.RE
.TP
.I "\-E, "\--no-endmarker
.RS
Do not use an endmarker.
This disables archive writing of archive endmarkers 
when writing an an archive,
and disables checking for these endmarkers
when reading an archive.
.RE
.TP
.I "\-F, "\--file-endmarker
.RS
Write endmarker as a file on a mounted medium,
or expect such an endmarker when reading from a mounted medium.
.RE
.TP
.I "\-D, "\--disable-filemark-fix
.RS
For debugging purpose only.
.RE
.TP
.I "\-V, "\--version
.RS
Print version information to stderr.
.RE
.SH EXIT STATUS
0=success, 1=read error, 2=write error, 3=wrong sequence
.SH EXAMPLE
You can use \fBmultibuf\fR without \fBKBackup\fR. An example:
.br
tar czvf - | multibuf -w -m 10 /dev/tape
.br
This will write a tar file using double buffering and possibly
spanning multiple physical volumes.
.SH BUGS
\fBmultibuf\fR uses the system(3) function internally.
See the
.BR system( 3 )
man page for caveats regarding the use of this function in
setuid and setgid programs.
.SH SEE ALSO
.BR dialog( 1 )
.br
.BR kbackup( 1 )
.br
.BR mt( 1 )
.SH AUTHOR
Karsten Ballueder 
.I Ballueder@usa.net
.SH COPYRIGHT
\fBmultibuf\fR is part of the \fBKBackup\fR package and protected
by the GNU GENERAL PUBLIC LICENSE, Version 2.

